apiVersion: v1
kind: Secret
metadata:
  name: super-secret-db-creds
  namespace: battleground
type: Opaque
data:
  # username: admin (base64)
  username: YWRtaW4=
  # password: ThisIsThePassword123! (base64)
  password: VGhpc0lzVGhlUGFzc3dvcmQxMjMh
